### ISSUE TITLE
current event is not displaying

### ISSUE THREAD

**Issue by soullessschizo** [JoeDuncko/easwbf2-events#2]
debugger shows some errors 

Uncaught TypeError: n is not a function
    <anonymous> index.js:8
    <anonymous> +esm:7
[index.js:8:38](https://cdn.jsdelivr.net/npm/date-fns@2.30.0/isDate/index.js)
    <anonymous> index.js:8
    <anonymous> +esm:7
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://esm.run/date-fns
Source Map URL: /sm/44f6639c14d8c1be00b5015db9a3c36d1c3ee723df90dd572c02186ba04368d6.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://esm.run/date-fns-tz
Source Map URL: /sm/cb262441d57a453a1201b43a151da408562d864e2b149b04252bfb2ff358619a.map

**Comment by JoeDuncko** [comment]
Sorry it took me until now to notice this!

I'm seeing the issue as well. I think what's causing this is also causing https://github.com/date-fns/date-fns/issues/3430 .

I tried reducing the version of date-fns, but date-fns-tz always brings in the latest version of date-fns along with it, even when I try to go to previous versions.

I guess my options are either to move to importing date-fns in a different way, or holding out for a fix from the date-fns team.

I'll give it another week, and go from there.

**Comment by JoeDuncko** [comment]
Fixed! See https://github.com/date-fns/date-fns/issues/3405#issuecomment-1533181148

**Comment by JoeDuncko** [comment]
This is an issue again :/
